const ReferencesActionsTypes = {
    FETCH_REFERENCES_START : 'FETCH_REFERENCES_START',
    FETCH_REFERENCES_SUCCESS : 'FETCH_REFERENCES_SUCCESS',
    FETCH_REFERENCES_FAILURE : 'FETCH_REFERENCES_FAILURE',
};

export default ReferencesActionsTypes;
