const ServicesActionsTypes = {
    FETCH_SERVICES_START : 'FETCH_SERVICES_START',
    FETCH_SERVICES_SUCCESS : 'FETCH_SERVICES_SUCCESS',
    FETCH_SERVICES_FAILURE : 'FETCH_SERVICES_FAILURE',
};

export default ServicesActionsTypes;
